<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-RNVS.ECommerce.Web-6e162ea6-636b-46a7-942a-68bb90547260</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="AWSSDK.Core" Version="4.0.1.1" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.7.12" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.26.0" />
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.1.11" />
    <PackageReference Include="Fido2" Version="4.0.0" />
    <PackageReference Include="Fido2.Models" Version="4.0.0" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="itext7" Version="9.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.10" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.14.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="Otp.NET" Version="1.4.0" />
    <PackageReference Include="PDFsharp" Version="6.2.2" />
    <PackageReference Include="Polly" Version="8.6.4" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
    <PackageReference Include="QuestPDF" Version="2025.7.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.Map" Version="1.0.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageReference Include="StackExchange.Redis" Version="2.9.32" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RNVS.ECommerce.Application\RNVS.ECommerce.Application.csproj" />
    <ProjectReference Include="..\RNVS.ECommerce.Infrastructure\RNVS.ECommerce.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\RNVS.ECommerce.Infrastructure\Email\Templates\**\*.html">
      <Link>Email\Templates\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
